### ISSUE TITLE
variabel jquery di dalam json

### ISSUE THREAD

**Issue by syam-tamvan** [qwords/evote#1]
di view inventory/tabel.php line 144
ketika hendak memasukan hasil json ke dalam variabel.

variabelnya bisa di alert,
tapi ketika di masukan ke function, not found..
mengapa?

**Comment by agitnaeta** [comment]
Salah Penulisan tidak bisa menampilkan format data javascript dalam php. seharusnya di pecah dulu tread sudah di upload silahkan di cek
