### ISSUE TITLE
jquery div not detected

### ISSUE THREAD

**Issue by syam-tamvan** [qwords/evote#2]
git,,
aku kan ngeload jquery di dalam jquery

jquery ketiga itu menutup div di jquery yang ke dua tapi 
kenapa penutup div yang di ketiga selalu ga ke detect
akhibatnya layaoutnya jadi ga rapi..

filenya ada di inventori/pilih_kantor.php

oh iya git,,,
kayaknya git bash ku belum syncron sm ini..
aku coba push tp ga bisa

**Comment by agitnaeta** [comment]
Padahal gak usah load jquery di jquery itu cuman butuh 1 interface utama, dan 2 halaman pendukung dengan 1 part jquery .

misal di span 12 kan di bagi 3

1. 4 untuk form detail 
2. 4 buat select 
3. 4 buat detail barang 2

**Comment by agitnaeta** [comment]
Chek change log 
https://github.com/qwords/evote/commit/ec18de6a3692555aef62e1135614df2e1e58c818
