### ISSUE TITLE
Reset password user

### ISSUE THREAD

**Issue by agitnaeta** [qwords/evote#3]
Saya coba update password user dan saya tidak mengisi apapun, kemudian di klik submit dan berhasil di simpan.

Sekarang saya tidak bisa login

**Comment by syam-tamvan** [comment]
sippp sudah di perbaiki

Terima kasih klinik tong pang :v

**Comment by agitnaeta** [comment]
Saya rasa belum, Menggunakan Required saja tidak bisa jalan kalo di mozila?

**Comment by syam-tamvan** [comment]
enggak pakai required
tp pake exception di controllernya

**Comment by agitnaeta** [comment]
Coba kondisi update password di mozila, terus kosongkan dua duanya
